# coding=utf8
# Copyright © 2016-2019 Cask Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
#
# This file is generated by Hue when using ./build/env/bin/hue create_desktop_app cdap
# A similar setup file for hbase can be found here: https://github.com/cloudera/hue/blob/master/apps/hbase/setup.py
# This file will be used when app_reg command is applied

from setuptools import setup, find_packages
import os


def expand_package_data(src_dirs, strip=""):
  """
  Flatten all the files in the plugin's directory and is used by
  built-in setup scripts. Generated by Hue and may not be modified.
  """
  ret = []
  for src_dir in src_dirs:
    for path, dnames, fnames in os.walk(src_dir):
      for fname in fnames:
        ret.append(os.path.join(path, fname).replace(strip, ""))
  return ret


os.chdir(os.path.dirname(os.path.abspath(__file__)))
setup(
  name='cdap',
  version='0.1',
  url='https://github.com/cdapio/cdap-security-extn',
  description='Hue Integration with CDAP',
  author='Cask Data, Inc.',
  packages=find_packages('src'),
  package_dir={'': 'src'},
  install_requires=['setuptools', 'desktop'],
  entry_points={'desktop.sdk.application': 'cdap=cdap'},
  zip_safe=False,
  package_data={
    # Include static resources.  Package_data doesn't
    # deal well with directory globs, so we enumerate
    # the files manually.
    'cdap': expand_package_data(
      ['src/cdap/templates', 'src/cdap/static'],
      'src/cdap/')
  }
)
